### ISSUE TITLE
Run it again please

### ISSUE THREAD

**Issue by koderproxy** [jboss-set/eap-additional-testsuite#33]
https://github.com/jboss-set/eap-additional-testsuite/blob/9a6cb23bad35d647a37c9e0493b2a32b51f1c7ed/modules/testcases/jdkAll/Wildfly/pom.xml#L515

**Comment by koderproxy** [comment]
from my side i think there is a error in elytron dir pls have a look

**Comment by panossot** [comment]
I have checked it and the tests pass with jdk 8.0.161. Please, remind me, which jdk version you use?

**Comment by koderproxy** [comment]
JDK version 1.8.0_171

**Comment by panossot** [comment]
I have checked with JDK version 1.8.0_171 and the elytron tests pass :

panos@dhcp-10-40-5-80 eap-additional-testsuite]$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
[panos@dhcp-10-40-5-80 eap-additional-testsuite]$ mvn clean install -Dwildfly -Dstandalone -Dmodule=elytron

Results :
Tests run: 143, Failures: 0, Errors: 0, Skipped: 13

[INFO] Reactor Summary:
[INFO] 
[INFO] org.jboss:eap-additional-testsuite ................. SUCCESS [  2.036 s]
[INFO] eap additional testsuite: eap additional testsuite modules SUCCESS [  1.267 s]
[INFO] wildfly additional testsuite: additional testsuite for wildfly SUCCESS [  2.456 s]
[INFO] wildfly additional testsuite: elytron .............. SUCCESS [  0.527 s]
[INFO] wildfly additional testsuite: elytron : configuration SUCCESS [02:25 min]

**Comment by koderproxy** [comment]
When I was checked then it's show java execution error. Every time I
checked it show same error can u tell me each  step u follow .

**Comment by panossot** [comment]
1. I have downloaded jdk 1.8.0.171 from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
2. Opened a shell :
    2.1. export JAVA_HOME=/home/panos/JDK8_171/jdk-8u171-linux-x64/jdk1.8.0_171 (change it to your jdk path)
    2.2 export PATH=$JAVA_HOME/bin:$PATH
    2.3 java -version should be "1.8.0_171"
    2.4 Then I have built wildfly master : mvn clean install -DskipTests
    2.5 Then, export JBOSS_FOLDER="wildfly master dir"/dist/target/wildfly-13.0.0.Alpha1-SNAPSHOT
    2.6 export JBOSS_VERSION=13.0.0.Alpha1-SNAPSHOT
    2.7 From the parent dir of EAT I execute : mvn clean install -Dwildfly -Dstandalone -Dmodule=elytron

**Comment by koderproxy** [comment]
Ohk thanks I will try to follow these step

**Comment by panossot** [comment]
Since elytron was executed successfully, I am closing this issue.

**Comment by koderproxy** [comment]
Ohk thanks for helping me to build ELYTRON successfuly
